### PR TITLE
Feature/get-user-by-id

### PR DESCRIPTION
**Pull request by ugurcanarikan**
## About
Get user by its id

### Changes

-UserController.java ( userById function )

### CODE REVIEW

**Review by gokceuludogan — CHANGES_REQUESTED** [review]
The binary files named .DS_Store  are unnecessary. Please remove them. Also, there is a problem in the routing. To get by id we are using the routing like /user/idNo . In your case, the routing is /user?id=idNo. Please update the method following our routing policy for consistency.

**Review by smddzcy — CHANGES_REQUESTED** [review]
Routing should be changed as @gokceuludogan has said. Also, please add `.DS_Store` to the `.gitignore` file in our project root.

**Comment by ugurcanarikan** [comment]
I don't know why but there is always a binary file .DS_Store in the files modified page even though I have modified only UserController class.

**Review by gokceuludogan — CHANGES_REQUESTED** [review]
It is still not correct. Here the id is a parameter but it should be a path variable. You can check update or deleteById methods of UserController to see how the id must be used.

**Review by gokceuludogan — APPROVED** [review]

**Comment by gokceuludogan** [comment]
Seems fine :+1:

**Review by smddzcy — APPROVED** [review]

**Comment by smddzcy** [comment]
There are still some `.DS_Store` files but it's OK 😄 🚀

**Pull request merged**
